# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(511, 360)
        MainWindow.setStyleSheet("QLineEdit {\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"padding: 7px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.oldLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.oldLineEdit.setStyleSheet("")
        self.oldLineEdit.setObjectName("oldLineEdit")
        self.gridLayout.addWidget(self.oldLineEdit, 1, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setStyleSheet("margin-left: 10px;\n"
"margin-right: 10px;\n"
"padding-left: 20px;\n"
"padding-right: 20px;")
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 4, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.selectNewPlistButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectNewPlistButton.setObjectName("selectNewPlistButton")
        self.gridLayout.addWidget(self.selectNewPlistButton, 2, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 2)
        self.selectOldPlistButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectOldPlistButton.setObjectName("selectOldPlistButton")
        self.gridLayout.addWidget(self.selectOldPlistButton, 1, 1, 1, 1)
        self.newLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newLineEdit.setObjectName("newLineEdit")
        self.gridLayout.addWidget(self.newLineEdit, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fullDevRadioButton = QtWidgets.QRadioButton(self.frame)
        self.fullDevRadioButton.setObjectName("fullDevRadioButton")
        self.horizontalLayout.addWidget(self.fullDevRadioButton)
        self.consumerRadioButton = QtWidgets.QRadioButton(self.frame)
        self.consumerRadioButton.setObjectName("consumerRadioButton")
        self.horizontalLayout.addWidget(self.consumerRadioButton)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clips Content Bundle Generator"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.selectNewPlistButton.setText(_translate("MainWindow", "Select New .ccdoc"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:600;\">Welcome!</span></p>\n"
"<p align=\"center\" style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\'; font-size:13pt;\">This tool will compare changes between two ccdoc files.</span></p>\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:600;\">Instructions:</span><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\"><br />1. Select an old ccdoc file (eg. catalog 1.10.841)</span></p>\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">1. Select a new ccdoc file (eg. catalog 1.10.900)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica Neue\'; font-size:13pt;\">3. \'Run\' the script</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Helvetica Neue\'; font-size:13pt;\"><br /></p></body></html>"))
        self.selectOldPlistButton.setText(_translate("MainWindow", "Select Old .ccdoc"))
        self.fullDevRadioButton.setText(_translate("MainWindow", "Full Dev"))
        self.consumerRadioButton.setText(_translate("MainWindow", "Consumer"))
